/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import javax.swing.JOptionPane;
//Para maimport ang code or igamit as a reader to make the code work

/**
 * Login class extends JFrame to create a login GUI for user authentication.
 */
public class Login extends javax.swing.JFrame {

    // Mga variables para sa username, password, at uri ng user
    private static String usname, pass, type = "admin";

    // File path kung saan nakasave ang JSON data ng users
    private static String filepath = "D:\\AT4_RiveraBSIT1A\\src\\Data.json";

    // JSON parser para mabasa at ma-parse ang JSON file
    private static JSONParser jsonParser = new JSONParser();

    // JSON object ug array para sa pag-store sa user data
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();

    /**
     * Constructor para sa pag-initialize ng UI components
     */
    public Login() {
        initComponents(); // Tawagin ang method para ma-display ang UI components
    }

    /**
     * It initializes labels, text fields, buttons, and layouts
     na autogenerated sa netbeans
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        // UI elements
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Kulay ng background or color of the background
        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Label sa username
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 95, 84, -1));

        // Label sa password
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 139, 84, 40));

        // Text field para sa pag-input ng username
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 90, 114, 31));

        // Text field para sa pag-input ng password
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 144, 114, 32));

        // Button para i-clear ang input fields
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 214, 83, 32));

        // Button para mag-login
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 214, 101, 32));

        // Label para sa login title
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 18, 82, 40));

        // Background image of the code
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Students Account\\Downloads\\UIC-Campus3_kIeAovs.jpg"));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-670, 0, 1160, 320));

        pack(); // Ifix ang layout para makita or visible
    }

    /**
     * 
     * Event handler sa pag-login
     */
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {  
        try {
            // Taking the input mula sa username at password fields
            usname = Username.getText();
            pass = Password.getText();

            // I-check ang file at i-load ang user data
            filecheck();

            // Pag-check ng credentials
            int checker = 0;
            for (int a = 0; a < userlist.size(); a++) {
                JSONObject userobject = (JSONObject) userlist.get(a);
                String searcheduname = (String) userobject.get("username");
                String searchedpswd = (String) userobject.get("password");

                // Kung tumutugma ang username at password
                if (usname.equals(searcheduname) && pass.equals(searchedpswd)) {
                    checker++;
                    break;
                }
            }

            // Kung walang nahanap na account
            if (checker == 0) {
                JOptionPane.showMessageDialog(this, "Walang nakitang account.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            } else {
                this.dispose(); // Isara ang login window
                Dashboard x = new Dashboard(); // To open the Dashboard or ibrihan ang dashboard
                x.setVisible(true);
            }

        } catch (IOException | ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Event handler sa Clear button
     */
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {
        // I-clear ang input fields
        Username.setText("");
        Password.setText("");
    }

    /**
     * 
     * Method nga mabasa ug mo-parse sa user credentials from JSON file.
     */
    public void filecheck() throws FileNotFoundException, IOException, ParseException {
        FileReader reader = new FileReader(filepath);

        if (reader.ready()) {
            Scanner scan = new Scanner(reader);
            String line = "";
            
            // Basahin ang file line by line
            while (scan.hasNext()) {
                line = line + scan.nextLine();
            }

            reader.close(); // I-sarado ang file reader

            // if its not empty file, i-parse ang JSON data
            if (!line.equals("")) {
                reader.close();
                FileReader reader2 = new FileReader(filepath);
                record = (JSONObject) jsonParser.parse(reader2);
                userlist = (JSONArray) record.get("users");
                reader2.close();
            }
        }
    }

    // Variables declaration (auto-generated ng NetBeans)
    private javax.swing.JButton Clear;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
}

